package com.grovewindbooks.entity;
// Generated Jun 2, 2023, 10:30:47 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private String email;
	private String fullName;
	private String address;
	private String city;
	private String country;
	private String phoneNumber;
	private String zipCode;
	private String password;
	private Timestamp registerDate;
	private Set reviews = new HashSet(0);
	private Set bookOrders = new HashSet(0);

	public Customer() {
	}

	public Customer(int customerId, String email, String fullName, String address, String city, String country,
			String phoneNumber, String zipCode, String password, Timestamp registerDate) {
		this.customerId = customerId;
		this.email = email;
		this.fullName = fullName;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phoneNumber = phoneNumber;
		this.zipCode = zipCode;
		this.password = password;
		this.registerDate = registerDate;
	}

	public Customer(int customerId, String email, String fullName, String address, String city, String country,
			String phoneNumber, String zipCode, String password, Timestamp registerDate, Set reviews, Set bookOrders) {
		this.customerId = customerId;
		this.email = email;
		this.fullName = fullName;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phoneNumber = phoneNumber;
		this.zipCode = zipCode;
		this.password = password;
		this.registerDate = registerDate;
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Timestamp getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Timestamp registerDate) {
		this.registerDate = registerDate;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getBookOrders() {
		return this.bookOrders;
	}

	public void setBookOrders(Set bookOrders) {
		this.bookOrders = bookOrders;
	}

}
