package com.grovewindbooks.entity;
// Generated Jun 2, 2023, 10:30:47 AM by Hibernate Tools 6.1.5.Final

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {

	private Integer bookId;
	private Integer orderId;
	private int quantity;
	private String subtotal;

	public OrderDetailId() {
	}

	public OrderDetailId(int quantity, String subtotal) {
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public OrderDetailId(Integer bookId, Integer orderId, int quantity, String subtotal) {
		this.bookId = bookId;
		this.orderId = orderId;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(String subtotal) {
		this.subtotal = subtotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getBookId() == castOther.getBookId()) || (this.getBookId() != null
				&& castOther.getBookId() != null && this.getBookId().equals(castOther.getBookId())))
				&& ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
						&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& (this.getQuantity() == castOther.getQuantity())
				&& ((this.getSubtotal() == castOther.getSubtotal()) || (this.getSubtotal() != null
						&& castOther.getSubtotal() != null && this.getSubtotal().equals(castOther.getSubtotal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBookId() == null ? 0 : this.getBookId().hashCode());
		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (getSubtotal() == null ? 0 : this.getSubtotal().hashCode());
		return result;
	}

}
